---

- name: Adding asahi Repository
  apt_repository:
    repo: "ppa:tobhe/asahi"
    state: present
    update_cache: yes

- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400 #One day

